package cn.supreme.ws.spring_cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2018-12-04T07:49:34.949+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://server.cxf.ws.supreme.cn/", name = "WeatherInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherInterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryWeather", targetNamespace = "http://server.cxf.ws.supreme.cn/", className = "cn.supreme.ws.spring_cxf.client.QueryWeather")
    @WebMethod
    @ResponseWrapper(localName = "queryWeatherResponse", targetNamespace = "http://server.cxf.ws.supreme.cn/", className = "cn.supreme.ws.spring_cxf.client.QueryWeatherResponse")
    public java.lang.String queryWeather(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
